

[tool.poetry]
packages = [
  { include = "retail_data_product" },
]
name = "retail-data-product"
version = "0.1.0"
description = "This project aims to introduce the potential of mixing Domain Driven Design and hexagonal architecture style in data engineering projects that define data products."
authors = ["Kesav<jagermister26@outlook.net>"]
readme = "README.md"

[tool.poetry.scripts]
orders_pipeline = "retail_data_product.entrypoints.orders_pipeline:main"
orders_streaming = "retail_data_product.entrypoints.orders_streaming:main"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.4.2"
pydantic = "^2.12.0"
pandas = "^2.3.3"
pytest-cov = "^7.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pyspark = "^3.5.0"
delta-spark = "^3.2.0"