from ...data_governance import (
    TableDefinition,
    Schema,
    SchemaField,
    DataType,
)


CAMPAIGNS_RAW = TableDefinition(
    name="campaigns_raw",
    description="Raw marketing campaigns from CRM system.",
    schema=Schema(
        fields=(
            SchemaField(
                name="campaign_id",
                data_type=DataType.STRING,
                description="Unique campaign identifier",
            ),
            SchemaField(
                name="channel",
                data_type=DataType.STRING,
                description="Marketing channel (email, sms)",
            ),
            SchemaField(
                name="cost",
                data_type=DataType.DOUBLE,
                description="Total campaign cost",
            ),
            SchemaField(
                name="start_date",
                data_type=DataType.DATE,
                description="Campaign start date",
            ),
            SchemaField(
                name="end_date",
                data_type=DataType.DATE,
                description="Campaign end date",
            ),
        ),
    ),
    primary_key=("campaign_id",),
)


CAMPAIGNS_ENRICHED = TableDefinition(
    name="campaigns_enriched",
    description="""
    Enriched campaigns with:
    - Standardized channel names (lowercase, no spaces)
    - Calculated revenue per campaign from orders
    - Valid channels: email, sms
    """,
    schema=Schema(
        fields=(
            SchemaField(
                name="campaign_id",
                data_type=DataType.STRING,
                description="Unique campaign identifier",
            ),
            SchemaField(
                name="channel",
                data_type=DataType.STRING,
                description="Cleaned marketing channel: email or sms",
            ),
            SchemaField(
                name="cost",
                data_type=DataType.DOUBLE,
                description="Total campaign cost",
            ),
            SchemaField(
                name="start_date",
                data_type=DataType.DATE,
                description="Campaign start date",
            ),
            SchemaField(
                name="end_date",
                data_type=DataType.DATE,
                description="Campaign end date",
            ),
            SchemaField(
                name="campaign_revenue",
                data_type=DataType.DOUBLE,
                description="Total revenue generated by this campaign",
            ),
        ),
    ),
    primary_key=("campaign_id",),
)
