from typing import Type, Sequence

from ...ports import DataSource, DataTarget, DataFrameEngine, DataQualityLogger
from ..base_etl_use_case import BaseETLUseCase

from ....domain.data_governance import Dataframe, TableDefinition, DataQualityRule
from ....domain.retail.campaigns import (
    CAMPAIGNS_ENRICHED,
    CampaignIdNotNull,
    ValidChannelRule,
    CleanChannelRule,
    CalculateCampaignRevenueRule,
)


class EnrichCampaigns(BaseETLUseCase):
    """
    Silver Layer: Enrich campaign data by calculating revenue per campaign.

    This use case joins campaign data with order data to compute
    the total revenue generated by each marketing campaign.
    """

    def __init__(
        self,
        campaigns_source: DataSource,
        orders_source: DataSource,
        campaigns_enriched_target: DataTarget,
        dataframe_engine: Type[DataFrameEngine],
        data_quality_logger: DataQualityLogger,
    ):
        """
        Args:
            campaigns_source (DataSource): bronze.campaigns_raw table
            orders_source (DataSource): silver.orders_cleaned table
            campaigns_enriched_target (DataTarget): silver.campaigns_enriched table
            dataframe_engine (Type[DataFrameEngine]): data processing engine
            data_quality_logger (DataQualityLogger): logger for data quality results
        """
        super().__init__(
            campaigns_enriched_target, dataframe_engine, data_quality_logger
        )
        self._campaigns_source = campaigns_source
        self._orders_source = orders_source

    def fetch_data(self) -> Dataframe:
        return self._campaigns_source.fetch(self._dataframe_engine)

    def get_target_table(self) -> TableDefinition:
        return CAMPAIGNS_ENRICHED

    def get_quality_rules(self) -> Sequence[DataQualityRule]:
        return (CampaignIdNotNull(), ValidChannelRule())

    def get_transformation_rules(self) -> Sequence:
        orders_df = self._orders_source.fetch(self._dataframe_engine)
        return (
            CleanChannelRule(),
            CalculateCampaignRevenueRule(orders_df=orders_df),
        )
