from ...data_governance import (
    TableDefinition,
    Schema,
    SchemaField,
    DataType,
)


CAMPAIGN_ROIS = TableDefinition(
    name="campaign_rois",
    description="""
    Campaign Return on Investment metrics.

    ROI = (revenue - cost) / cost * 100

    Computed from enriched campaigns data.
    """,
    schema=Schema(
        fields=(
            SchemaField(
                name="campaign_id",
                data_type=DataType.STRING,
                description="Unique campaign identifier",
            ),
            SchemaField(
                name="channel",
                data_type=DataType.STRING,
                description="Marketing channel",
            ),
            SchemaField(
                name="cost",
                data_type=DataType.DOUBLE,
                description="Total campaign cost",
            ),
            SchemaField(
                name="campaign_revenue",
                data_type=DataType.DOUBLE,
                description="Total revenue generated by this campaign",
            ),
            SchemaField(
                name="roi",
                data_type=DataType.DOUBLE,
                description="Return on Investment percentage",
            ),
        ),
    ),
    primary_key=("campaign_id",),
)


DAILY_GROSS_SALES = TableDefinition(
    name="daily_gross_sales",
    description="""
    Daily aggregated gross sales metrics.

    Includes:
    - Total gross amount in EUR
    - Number of orders
    - Gap filling for dates with no sales (0 values)
    """,
    schema=Schema(
        fields=(
            SchemaField(
                name="order_date",
                data_type=DataType.DATE,
                description="Date of the aggregated sales",
            ),
            SchemaField(
                name="gross_sales_eur",
                data_type=DataType.DOUBLE,
                description="Total gross sales in EUR",
            ),
            SchemaField(
                name="order_count",
                data_type=DataType.INTEGER,
                description="Number of orders for the day",
            ),
        ),
    ),
    primary_key=("order_date",),
)
